name: GitHub Profile Summary and Snake Animation

on:
  schedule:
    - cron: "* */12 * * *"  # Execute every 12 hours
  workflow_dispatch:        # Allow manual triggering

jobs:
  build:
    name: Update Profile Data and Visualizations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release  # Update to latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: andersonbcn # Replace with actual GitHub username

      - name: Create Contribution Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: andersonbcn
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3 # Update to latest version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
